#!/bin/bash
###################################################################################
# Display cluster scores of pacemaker resources
# vim:set fileencoding=utf8 fileformat=unix filetype=shell tabstop=2 expandtab:
# @(#)$Id: showscores,v 1.15 2026/04/08 06:19:10 ralph Exp $
# (c) 2012-2026 by Ralph Roth, rose_swe@gmx.net
###################################################################################
## WARNING: This is for SLES12/SLES15, will not work on SLES9/10/11 whatever
## Tested with MLS7.9 (RHEL 7.9), so this should also work with RHEL9 & RHEL10
###################################################################################

if [ "$1" = "--help" ] || [ "$1" = "-h" ] || [ "$1" = "-?" ]
then
    echo "Pacemaker showscores (v3) - parsing crm/pcs resource scores"
    echo ""
    echo "---=[ Usage ]=---------------------------------------------"
    echo "$0 to display score information for all resources on all nodes sorted by resource name"
    echo ""
    echo "$0 <file> to display score information for all resources on all nodes"
    echo "sorted by resource name, where <file> is a file containing the output of"
    echo ""
    echo "'crm resource scores' or 'crm_simulate -sL'"

    exit 0
fi

source /etc/os-release		## get OS env
case "${ID}" in
	sles)	CMD="crm resource scores"
        ## HINT: Needs a fix, see issue#6 and see https://github.com/SUSE/suse-best-practices/issues/370
        ## HINT: See https://bugzilla.suse.com/show_bug.cgi?id=1210614 - Bug 1210614 - Duplicated entries for resource-stickiness and https://github.com/ClusterLabs/crmsh/pull/1174
        default_stickiness=$(crm_attribute -G -n resource-stickiness -t rsc_defaults -Q 2>/dev/null)
    ;;
	rhel|centos|fedora)  CMD="crm_simulate -sL"
        ## MLS7.9 (RHEL 7.9) does not support crm_attribute, so we have to parse the output of pcs property instead, which is a bit more error-prone, but should work for RHEL9/RHEL10 as well
        default_stickiness=$(pcs property | grep default-resource-stickiness: | awk '{print $2}')
    ;;

	*)	echo "[!!] Unsupported Operation System: $ID"; exit 1 ;;
esac

## OK, a quick hack to allow parsing of a file instead of executing the command, e.g. for testing or if the cluster framework is not running
if [ "$#" -gt 0 ] && [ -r "${1}" ]
then
    CMD="cat $1"
fi

# bug detected with non-standard locales
#
export LC_ALL=C

default_migrationthreshold=$(crm_attribute -G -n migration-threshold -t rsc_defaults -Q 2>/dev/null)

## TODO: Stop here if an error is raised -> cluster framework not running (e.g. crm cluster stop)

echo "rsc_defaults: resource-stickiness=${default_stickiness}   migration-threshold=${default_migrationthreshold}"
echo ""

## TODO: Maybe replace in the tr command ":" with "_" for better readability?
## TODO: Sort host before outputting them

# 1. Capture the scores and clean them
# 2. Use AWK to build a matrix, preserving -INFINITY
# 3. Sort the host headers for a consistent table layout
# Execute and Parse
$CMD | sort | awk ' / allocation score on / {
    # $2=resource, $6=host, $NF=score
    print $2, $6, $NF;
}' | tr -d ":" | sort -u | \
awk '
{
    r=$1; h=$2; s=$3;

    # Logic to handle both INFINITY types:
    # 1. If we already have -INFINITY, never overwrite (Hard Restriction)
    if (a[r][h] == "-INFINITY") {
        next
    }

    # 2. If the new score is -INFINITY, it always wins
    if (s == "-INFINITY") {
        a[r][h] = s
        hosts[h]++
        next
    }

    # 3. If we already have INFINITY, only -INFINITY can overwrite it
    if (a[r][h] == "INFINITY") {
        next
    }

    # 4. Otherwise, store the score
    a[r][h] = s
    hosts[h]++
}

END {
    # Sort Host Headers
    n_h = 0
    for (h in hosts) sorted_hosts[++n_h] = h
    asort(sorted_hosts)

    # Print Header
    printf("##[ Resource ]#####[ Nodes ]##   ")
    for (i=1; i<=n_h; i++) printf ("%18s ", sorted_hosts[i])
    printf ("\n")

    # Sort and Print Resources
    n_r = 0
    for (r in a) res_list[++n_r] = r
    asort(res_list)

    for (i=1; i<=n_r; i++) {
        r = res_list[i]
        printf("%-32s ", r)
        for (j=1; j<=n_h; j++) {
            h = sorted_hosts[j]
            val = (h in a[r]) ? a[r][h] : "0"
            printf("%18s ", val)
        }
        printf ("\n")
    }
}
'

echo ""
echo "Showscore taken on node: $(hostname) ($PRETTY_NAME) at $(date)"
